const calls=[
 {name:'محمد أحمد',issue:'الإنترنت عندي بيفصل كل شوية ومحتاج حل سريع.',answers:[['أفهم حضرتك، خلينا نفحص الخط ونحل المشكلة خطوة بخطوة.','good'],['لازم تستنى لحد ما المشكلة تتحل.','bad'],['دي مش مشكلة عندنا.','bad']]},
 {name:'سارة محمود',issue:'اتخصم مني مبلغ مرتين في نفس العملية.',answers:[['آسف على الإزعاج، هراجع العملية وأتأكد من حالة الخصم مع حضرتك.','good'],['أكيد البنك هو السبب.','bad'],['مش هقدر أساعدك في الموضوع ده.','bad']]},
 {name:'أحمد علي',issue:'عايز أغير الباقة بتاعتي لأعلى باقة.',answers:[['بكل تأكيد، هراجع الباقات المتاحة وأساعد حضرتك تختار الأنسب.','good'],['غيرها من التطبيق وخلاص.','bad'],['مفيش باقات تانية.','bad']]}
];
let index=0,answered=false,startTime=0,totalSeconds=0,score=100,csat=100;
const $=id=>document.getElementById(id);
const format=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
function renderCall(){const c=calls[index%calls.length];$('caller').textContent=`📞 العميل: ${c.name}`;$('caller').classList.remove('hidden');$('scenario').innerHTML=`<h2>مشكلة العميل</h2><p>"${c.issue}"</p>`;$('choices').innerHTML='';c.answers.forEach(([text,type])=>{const b=document.createElement('button');b.className='choice';b.textContent=text;b.onclick=()=>answer(type);$('choices').appendChild(b)});$('status').textContent='مكالمة واردة — اختار أفضل رد';$('answerBtn').classList.add('hidden');startTime=Date.now();answered=false}
function answer(type){if(answered)return;answered=true;const duration=Math.max(1,Math.round((Date.now()-startTime)/1000));totalSeconds+=duration;score=Math.max(0,score+(type==='good'?2:-12));csat=Math.max(0,csat+(type==='good'?0:-15));$('calls').textContent=index+1;$('quality').textContent=`${score}%`;$('csat').textContent=`${csat}%`;$('aht').textContent=format(Math.round(totalSeconds/(index+1)));$('feedback').textContent=type==='good'?'✅ رد ممتاز! العميل يشعر بالاهتمام وتم اتباع أسلوب خدمة احترافي.':'⚠️ رد غير مناسب. حاول إظهار التعاطف، جمع المعلومات، ثم تقديم حل واضح.';$('feedback').classList.remove('hidden');$('status').textContent=type==='good'?'تم حل المكالمة بنجاح':'المكالمة انتهت بجودة منخفضة';$('choices').querySelectorAll('button').forEach(b=>b.disabled=true);$('answerBtn').textContent='📞 المكالمة التالية';$('answerBtn').classList.remove('hidden');}
$('answerBtn').onclick=()=>{if(answered){index++;$('feedback').classList.add('hidden');$('answerBtn').textContent='جارٍ الاتصال...';setTimeout(renderCall,350)}else renderCall()};
